// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLAxEsxsH_PYP2dvB2lr7E4gV8wcP-Q0',
    appId: '1:987372302004:web:e92146bec69558682031e1',
    messagingSenderId: '987372302004',
    projectId: 'deli-hobby',
    authDomain: 'deli-hobby.firebaseapp.com',
    storageBucket: 'deli-hobby.firebasestorage.app',
    measurementId: 'G-BLKNFRGEYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGAOlAGD5iTFYqXVt9FJNlmJ891U5HVY',
    appId: '1:987372302004:android:2a77a7428b25fbd02031e1',
    messagingSenderId: '987372302004',
    projectId: 'deli-hobby',
    storageBucket: 'deli-hobby.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe-Dcx1rydwCuG6CBeBVHBlMRvEZTQt9E',
    appId: '1:987372302004:ios:28068baea3020ee22031e1',
    messagingSenderId: '987372302004',
    projectId: 'deli-hobby',
    storageBucket: 'deli-hobby.firebasestorage.app',
    iosBundleId: 'com.example.deliHobby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe-Dcx1rydwCuG6CBeBVHBlMRvEZTQt9E',
    appId: '1:987372302004:ios:28068baea3020ee22031e1',
    messagingSenderId: '987372302004',
    projectId: 'deli-hobby',
    storageBucket: 'deli-hobby.firebasestorage.app',
    iosBundleId: 'com.example.deliHobby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJLAxEsxsH_PYP2dvB2lr7E4gV8wcP-Q0',
    appId: '1:987372302004:web:6bfbddb1483885912031e1',
    messagingSenderId: '987372302004',
    projectId: 'deli-hobby',
    authDomain: 'deli-hobby.firebaseapp.com',
    storageBucket: 'deli-hobby.firebasestorage.app',
    measurementId: 'G-0YZWB8J0H9',
  );

}